// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// obj3Cpp
NumericVector obj3Cpp(const NumericVector& uR, const NumericVector& xj, const NumericVector& weightsR, const double band);
RcppExport SEXP _MNARclust_obj3Cpp(SEXP uRSEXP, SEXP xjSEXP, SEXP weightsRSEXP, SEXP bandSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type uR(uRSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type xj(xjSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weightsR(weightsRSEXP);
    Rcpp::traits::input_parameter< const double >::type band(bandSEXP);
    rcpp_result_gen = Rcpp::wrap(obj3Cpp(uR, xj, weightsR, band));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MNARclust_obj3Cpp", (DL_FUNC) &_MNARclust_obj3Cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_MNARclust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
